### ISSUE TITLE
I've got some error 

### ISSUE THREAD

**Issue by thomastian** [homeassistantchina/custom_components#4]
2017-09-12 09:27:38 INFO (SyncWorker_3) [homeassistant.loader] Loaded persistent_notification from homeassistant.components.persistent_notification
2017-09-12 09:27:38 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform chuangmi_ir
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 164, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/tianyucheng/.homeassistant/custom_components/switch/chuangmi_ir.py", line 103, in setup_platform
    ir_remote = miio.device(host, token)
  File "/Users/tianyucheng/.homeassistant/deps/lib/python/site-packages/miio/miio.py", line 16, in __init__
    self.token = bytes.fromhex(token)
ValueError: non-hexadecimal number found in fromhex() arg at position 0

hass 0.52.1

**Comment by thomastian** [comment]
switch:
  - platform: chuangmi_ir
    name: "livingroomirremote"
    host: 10.1.128.55
    token: XXXXXXXXXXXXXXXXXXXX
    timeout: 20
    switches:
      reciever:
        command_on: ''
        command_off: ''

**Comment by thomastian** [comment]
switch:

platform: chuangmi_ir
name: "livingroomirremote"
host: x.x.x.x
token: XXXXXXXXXXXXXXXXXXXX
timeout: 20
switches:
reciever:
command_on: ''
command_off: ''

**Comment by thomastian** [comment]
sorry,I had found wrong  number "token".
